// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW89F4j-6KPZZ67pGuXl-ojHohg_vBhUg',
    appId: '1:401589380882:android:d7fdcf920753079c96b5cb',
    messagingSenderId: '401589380882',
    projectId: 'smart-sensors-cbad5',
    storageBucket: 'smart-sensors-cbad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwcUyjcgPMiCYhfSgKa87v9mnBx346uA',
    appId: '1:401589380882:ios:5d8c4fac91e2cc8596b5cb',
    messagingSenderId: '401589380882',
    projectId: 'smart-sensors-cbad5',
    storageBucket: 'smart-sensors-cbad5.appspot.com',
    iosBundleId: 'com.hnsolutions.smartSensors',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgwgiQkt670ZeNoLfdtKm_gSb85nz6yU',
    appId: '1:401589380882:web:bf95bb0c73d66f4696b5cb',
    messagingSenderId: '401589380882',
    projectId: 'smart-sensors-cbad5',
    authDomain: 'smart-sensors-cbad5.firebaseapp.com',
    storageBucket: 'smart-sensors-cbad5.appspot.com',
    measurementId: 'G-BR7VLRXREJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwcUyjcgPMiCYhfSgKa87v9mnBx346uA',
    appId: '1:401589380882:ios:5d8c4fac91e2cc8596b5cb',
    messagingSenderId: '401589380882',
    projectId: 'smart-sensors-cbad5',
    storageBucket: 'smart-sensors-cbad5.appspot.com',
    iosBundleId: 'com.hnsolutions.smartSensors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgwgiQkt670ZeNoLfdtKm_gSb85nz6yU',
    appId: '1:401589380882:web:464be18e01c4745b96b5cb',
    messagingSenderId: '401589380882',
    projectId: 'smart-sensors-cbad5',
    authDomain: 'smart-sensors-cbad5.firebaseapp.com',
    storageBucket: 'smart-sensors-cbad5.appspot.com',
    measurementId: 'G-4Y41RD0WPL',
  );

}